package com.berstek.uhacpayso.staticData;

import java.util.ArrayList;
import java.util.List;

public class CurrenciesData {
	
	private static String[] countries ={
		"Afghanistan",
		"Albania",

		"Algeria",
		"American Samoa",
		"Andorra",
		"Angola",
		"Anguilla",
		"Antigua and Barbuda",
		"Argentina",
		"Armenia",
		"Aruba",
		"Australia",
		"Austria",
		"Azerbaijan",
		"Bahamas",
		"Bahrain",
		"Bangladesh",
		"Barbados",
		"Belarus",
		"Belgium",
		"Belize",
		"Benin",
		"Bermuda",
		"Bhutan",
		"Bolivia",
		"Bosnia-Herzegovina",
		"Botswana",
		"Brazil",
		"British Indian Ocean Territory",
		"Brunei",
		"Bulgaria",
		"Burkina Faso",
		"Burma",
		"Burundi",
		"Cambodia",
		"Cameroon",
		"Canada",
		"Canton and Enderbury Islands",
		"Cape Verde",
		"Cayman Islands",
		"Central African Republic",
		"Chad",
		"Chile",
		"China",
		"Christmas Island",
		"Cocos (Keeling) Islands",
		"Colombia",
		"Comoros",
		"Congo",
		"Congo, Democratic Republic",
		"Cook Islands",
		"Costa Rica",
		"C�te d'Ivoire",
		"Croatia",
		"Cuba",
		"Cyprus",
		"Czech Republic",
		"Denmark",
		"Djibouti",
		"Dominica",
		"Dominican Republic",
		"Dronning Maud Land",
		"East Timor",
		"Equador",
		"Egypt",
		"El Salvador",
		"Equatorial Guinea",
		"Eritrea",
		"Estonia",
		"Ethiopia",
		"Faeroe Islands (F�royar)",
		"Falkland Islands",
		"Fiji",
		"Finland",
		"France",
		"French Guiana",
		"French Polinesia",
		"Gabon",
		"Gambia",
		"Georgia",
		"Germany",
		"Ghana",
		"Gibraltar",
		"Great Britain",
		"Greece",
		"Greendland",
		"Grenada",
		"Guadeloupe",
		"Guam",
		"Guatemala",
		"Guernsey",
		"Guinea-Bisau",
		"Guinea",
		"Guyana",
		"Haiti",
		"Heard and McDonald Islands",
		"Honduras",
		"Hong Kong",
		"Hungary",
		"Iceland",
		"India",
		"Indonesia",
		"Internatonal Monetary Fund",
		"Iran",
		"Iraq",
		"Ireland",
		"Isle of Man",
		"Israel",
		"Italy",
		"Ivory Coast",
		"Jamaica",
		"Japan",
		"Jersey",
		"Johnston Island",
		"Jordan",
		"Kampuchea",
		"Kazakhstan",
		"Kenya",
		"Kiribati",
		"Korea, North",
		"Korea, South",
		"Kuwait",
		"Kyrgyzstan",
		"Laos",
		"Latvia",
		"Lebanon",
		"Lesotho",
		"Liberia",
		"Libya",
		"Liechtenstein",
		"Lithuana",
		"Luxembourg",
		"Macau",
		"Macedonia (Former Yug. Rep.)",
		"Madagascar",
		"Malawi",
		"Malaysia",
		"Maldives",
		"Mali",
		"Malta",
		"Martinique",
		"Mauritania",
		"Mauritius",
		"Mayotte",
		"Micronesia",
		"Midway Islands",
		"Mexico",
		"Moldova",
		"Monaco",
		"Mongolia",
		"Montenegro",
		"Montserrat",
		"Morocco",
		"Mozambique",
		"Myanmar",
		"Nauru",
		"Namibia",
		"Nepal",
		"Netherlands Antilles",
		"Netherlands",
		"New Caledonia",
		"New Zealand",
		"Nicaragua",
		"Niger",
		"Nigeria",
		"Niue",
		"Norfolk Island",
		"Northern Mariana Islands",
		"Norway",
		"Oman",
		"Pakistan",
		"Palau",
		"Panama",
		"Papua New Guinea",
		"Paraguay",
		"Peru",
		"Philippines",
		"Pitcaim Island",
		"Poland",
		"Portugal",
		"Puerto Rico",
		"Qatar",
		"Reunion",
		"Romania",
		"Russia",
		"Rwanda",
		"Samoa (Western)",
		"Samoa (America)",
		"San Marino",
		"S�o Tom� and Pr�ncipe",
		"Saudi Arabia",
		"S�n�gal",
		"Serbia",
		"Seychelles",
		"Sierra Leone",
		"Singapore",
		"Slovakia",
		"Slovenia",
		"Solomon Islands",
		"Somalia",
		"South Africa",
		"Spain",
		"Sri Lanka",
		"St. Helena",
		"St. Kitts and Nevis",
		"St. Lucia",
		"St. Vincent and the Grenadines",
		"Sudan",
		"Suriname",
		"Svalbard and Jan Mayen Islands",
		"Swaziland",
		"Sweden",
		"Switzrland",
		"Syria",
		"Tahiti",
		"Taiwan",
		"Tajikistan",
		"Tanzania",
		"Thailand",
		"Timor-Leste",
		"Togo",
		"Trinidad and Tobago",
		"Tunisia",
		"Turkey",
		"Turkmenistan",
		"Turks and Caicos Islands",
		"Tuvalu",
		"Uganda",
		"Ukraine",
		"United Arab Emirates",
		"United Kingdom",
		"United States of America",
		"Upper Volta",
		"Uruguary",
		"Uzbekistan",
		"Vanuatu",
		"Vatican",
		"Venezuela",
		"Vietnam",
		"Virgin Islands",
		"Wake Island",
		"Wallis and Futuna Islands",
		"Western Sahara",
		"Western Samoa",
		"Yemen",
		"Za�re",
		"Zambia",
		"Zimbabwe"
	};

	private static String[] currencies = {
		"Afghan afghani",
		"Albnian lek",
		"Algerian dinar",
		"United States dollar",
		"European euro",
		"Angolan kwanza",
		"East Caribbean dollar",
		"East Caribbean dollar",
		"Argentine peso",
		"Armenian dram",
		"Aruban florin",
		"Australian dollar",
		"European euro",
		"Azerbaijani manar",
		"Bahamian dollar",
		"Bahraini dinar",
		"Bangladeshi taka",
		"Barbadian dollar",
		"Belarusian ruble",
		"European euro",
		"Belize dollar",
		"West African CFA franc",
		"Bermudian dollar",
		"Bhutanese ngultrum",
		"Bolivian boliviano",
		"Bosnia and Herzegovina konvertibilna marka",
		"Botswana pula",
		"Brazilian real",
		"British pound",
		"Brunei dollar",
		"Bulgarian lev",
		"West African CFA franc",
		"Myanma kyat",
		"Burundi franc",
		"Cambodian riel",
		"Central African CFA franc",
		"Canadian dollar",
		"Australian dollar",
		"Cape Verdean escudo",
		"Cayman Islands dollar",
		"Central African CFA franc",
		"Central African CFA franc",
		"Chilean peso",
		"Chinese renmibi",
		"Australian dollar",
		"Austrilian dollar",
		"Colombian peso",
		"Comorian franc",
		"Central African CFA franc",
		"Congolese franc",
		"New Zealand dollar",
		"Costa Rican colon",
		"West African CFA franc",
		"Croatian kuna",
		"Cuban peso",
		"European euro",
		"Czech koruna",
		"Danish krone",
		"Djiboutian franc",
		"East Caribbean dollar",
		"Dominican peso",
		"Norwegian krone",
		"U.S. Dollar",
		"U.S. Dollar",
		"Egyptian pound",
		"U.S. Dollar",
		"Central African CFA franc",
		"Eritrean nakfa",
		"Estonian kroon",
		"Ethiopian birr",
		"Danish krone",
		"Falkland Islands pound",
		"Fijian dollar",
		"European euro",
		"European euro",
		"European euro",
		"CFP franc",
		"Central African CFA franc",
		"Gambian dalasi",
		"Georgian lari",
		"European euro",
		"Ghanaian cedi",
		"Gibraltar pound",
		"British pound",
		"European euro",
		"Danish krone",
		"East Caribbean dollar",
		"European euro",
		"United States dollar",
		"Guatemalan quetzal",
		"British pound",
		"West African CFA franc",
		"Guinean franc",
		"Guyanese dollar",
		"Haitian gourde",
		"Australian dollar",
		"Honduran lempira",
		"Hong Kong dollar",
		"Hungarian forint",
		"Icelandic kr�na",
		"Indian rupee",
		"Indonesian rupiah",
		"Special Drawing Rights",
		"Iranian rial",
		"Iraqi dinar",
		"European euro",
		"British pound",
		"Israeli new sheqel",
		"European euro",
		"West African CFA franc",
		"Jamaican dollar",
		"Japanese yen",
		"British pound",
		"United States dollar",
		"Jordanian dinar",
		"Cambodian riel",
		"Kazakhstani tenge",
		"Kenyan shilling",
		"Austrilian dollar",
		"North Korean won",
		"South Korean won",
		"Kuwaiti dinar",
		"Kyrgyzstani som",
		"Lao kip",
		"Latvian lats",
		"Lebanese lira",
		"Lesotho loti",
		"Liberian dollar",
		"Libyan dinar",
		"Swiss Franc",
		"Lithuanian litas",
		"European euro",
		"Macanese pataca",
		"Macedonian denar",
		"Malagasy ariary",
		"Malawian kwacha",
		"Malaysian ringgit",
		"Maldivian rufiyaa",
		"West African CFA franc",
		"European Euro",
		"European euro",
		"Mauritanian ouguiya",
		"Mauritian rupee",
		"European euro",
		"Unites States dollar",
		"Unites States dollar",
		"Mexican peso",
		"Moldovan leu",
		"European euro",
		"Mongolian tugrik",
		"European euro",
		"East Caribbean dollar",
		"Moroccan dirham",
		"Mozambican metical",
		"Myanma kyat",
		"Autralian dollar",
		"Namibian dollar",
		"Nepalese rupee",
		"Netherlands Antillean gulden",
		"European euro",
		"CFP franc",
		"New Zealand dollar",
		"Nicaraguan c�rdoba",
		"West African CFA franc",
		"Nigerian naira",
		"New Zealand dollar",
		"Australian dollar",
		"United States dollar",
		"Norwegian krone",
		"Omani rial",
		"Pakistani rupee",
		"United States dollar",
		"Panamanian balboa",
		"Papua New Guinean kina",
		"Paraguayan guarani",
		"Peruvian neuvo sol",
		"Philippine peso",
		"New Zealand dollar",
		"Polish zloty",
		"European euro",
		"United States dollar",
		"Qatari riyal",
		"European euro",
		"Romanian leu",
		"Russian ruble",
		"Rwandan franc",
		"Samoan tala",
		"United States dollar",
		"European euro",
		"S�o Tom� and Pr�ncipe dobra",
		"Saudi riyal",
		"West African CFA franc",
		"Serbian dinar",
		"Seychellois rupee",
		"Sierra Leonean leone",
		"Singapore dollar",
		"European euro",
		"European euro",
		"Solomon Islands dollar",
		"Somali shilling",
		"South African rand",
		"European euro",
		"Sri Lankan rupee",
		"Saint Helena pound",
		"East Caribbean dollar",
		"East Caribbean dollar",
		"East Caribbean dollar",
		"Sudanese pound",
		"Surinamese dollar",
		"Norwegian krone",
		"Swazi lilangeni",
		"Swedish krona",
		"Swiss franc",
		"Syrian pound",
		"CFP franc",
		"New Taiwan dollar",
		"Tajikistani somoni",
		"Tanzanian shilling",
		"Thai baht",
		"U.S. dollar",
		"West African CFA franc",
		"Trinidad and Tobago dollar",
		"Tunisian dinar",
		"Turkish new lira",
		"Turkmen manat",
		"United States dollar",
		"Australian dollar",
		"Ugandan shilling",
		"Ukrainian hryvnia",
		"UAE dirham",
		"British pound",
		"United States dollar",
		"West African CFA franc",
		"Uruguayan peso",
		"uzbekistani som",
		"Vanuatu vatu",
		"European euro",
		"Venezuelan bolivar",
		"Vietnamese dong",
		"United States dollar",
		"United States dollar",
		"CFP franc",
		"European Euro",
		"Samoan tala",
		"Yemeni rial",
		"Congolese franc",
		"Zambian kwacha",
		"Zimbabwean dollar"
	};
	
	private static String[] isos = {
		"AFN",
		"ALL",
		"DZD",
		"USD",
		"EUR",
		"AOA",
		"XCD",
		"XCD",
		"ARS",
		"AMD",
		"AWG",
		"AUD",
		"EUR",
		"AZN",
		"BSD",
		"BHD",
		"BDT",
		"BBD",
		"BYR",
		"EUR",
		"BZD",
		"XOF",
		"BMD",
		"BTN",
		"BOB",
		"BAM",
		"BWP",
		"BRL",
		"GBP",
		"BND",
		"BGN",
		"XOF",
		"MMK",
		"BIF",
		"KHR",
		"AF",
		"CAD",
		"AUD",
		"CVE",
		"KYD",
		"XAF",
		"XAF",
		"CLP",
		"CNY",
		"AUD",
		"AUD",
		"COP",
		"KMF",
		"XAF",
		"CDF",
		"NZD",
		"CRC",
		"XOF",
		"HRK",
		"CUC",
		"EUR",
		"CZK",
		"DKK",
		"DJF",
		"XCD",
		"DOP",
		"NOK",
		"USD",
		"USD",
		"EGP",
		"USD",
		"GQE",
		"ERN",
		"EEK",
		"ETB",
		"DKK",
		"FKP",
		"FJD",
		"EUR",
		"EUR",
		"EUR",
		"XPF",
		"XAF",
		"GMD",
		"GEL",
		"EUR",
		"GHS",
		"GIP",
		"GBP",
		"EUR",
		"DKK",
		"XCD",
		"EUR",
		"USD",
		"GTQ",
		"GBP",
		"XOF",
		"GNF",
		"GYD",
		"HTG",
		"AUD",
		"HNL",
		"HKD",
		"HUF",
		"ISK",
		"INR",
		"IDR",
		"XDR",
		"IRR",
		"IQD",
		"EUR",
		"GBP",
		"ILS",
		"EUR",
		"XOF",
		"JMD",
		"JPY",
		"GBP",
		"USD",
		"JOD",
		"KHR",
		"KZT",
		"KES",
		"AUD",
		"KPW",
		"KRW",
		"KWD",
		"KGS",
		"LAK",
		"LVL",
		"LBP",
		"LSL",
		"LRD",
		"LYD",
		"CHF",
		"LTL",
		"EUR",
		"MOP",
		"MKD",
		"MGA",
		"MWK",
		"MYR",
		"MVR",
		"XOF",
		"EUR",
		"EUR",
		"MRO",
		"MUR",
		"EUR",
		"USD",
		"USD",
		"MXN",
		"MDL",
		"EUR",
		"MNT",
		"EUR",
		"XCD",
		"MAD",
		"MZM",
		"MMK",
		"AUD",
		"NAD",
		"NPR",
		"ANG",
		"EUR",
		"XPF",
		"NZD",
		"NIO",
		"XOF",
		"NBN",
		"NZD",
		"AUD",
		"USD",
		"NOK",
		"OMR",
		"PKR",
		"USD",
		"PAB",
		"PGK",
		"PYG",
		"PEN",
		"PHP",
		"NZD",
		"PLN",
		"EUR",
		"USD",
		"QAR",
		"EUR",
		"RON",
		"RUB",
		"RWF",
		"WST",
		"USD",
		"EUR",
		"STD",
		"SAR",
		"XOF",
		"RSD",
		"SCR",
		"SLL",
		"SGD",
		"EUR",
		"EUR",
		"SBD",
		"SOS",
		"ZAR",
		"EUR",
		"LKR",
		"SHP",
		"XCD",
		"XCD",
		"XCD",
		"SDG",
		"SRD",
		"NOK",
		"SZL",
		"SEK",
		"CHF",
		"SYP",
		"XPF",
		"TWD",
		"TJS",
		"TZS",
		"THB",
		"USD",
		"XOF",
		"TTD",
		"TND",
		"TRY",
		"TMT",
		"USD",
		"AUD",
		"UGX",
		"UAH",
		"AED",
		"GBP",
		"USD",
		"XOF",
		"UYU",
		"UZS",
		"VUV",
		"EUR",
		"VEB",
		"VND",
		"USD",
		"USD",
		"XPF",
		"EUR",
		"WST",
		"YER",
		"CDF",
		"ZMK",
		"ZWR"
	};
	
	private static String[] symbols = {
            "",
            "",
            "",
            "US$",
            "€",
            "",
            "EC$",
            "EC$",
            "",
            "",
            "ƒ",
            "$",
            "€",
            "",
            "B$",
            "",
            "",
            "Bds$",
            "Br",
            "€",
            "BZ$",
            "CFA",
            "BD$",
            "Nu.",
            "Bs.",
            "KM",
            "P",
            "R$",
            "£",
            "B$",
            "",
            "CFA",
            "K",
            "FBu",
            "",
            "CFA",
            "$",
            "$",
            "Esc",
            "KY$",
            "CFA",
            "CFA",
            "$",
            "¥",
            "$",
            "$",
            "Col$",
            "",
            "CFA",
            "F",
            "NZ$",
            "₡",//Costa Rica
            "CFA",
            "kn",
            "$",
            "€",
            "Kč",//Czech Republic
            "Kr",
            "Fdj",
            "EC$",
            "RD$",
            "kr",
            "US$",
            "US$",
            "£",
            "US$",
            "CFA",
            "Nfa",
            "KR",
            "Br",
            "Kr",
            "£",
            "FJ$",
            "€",
            "€",
            "€",
            "F",
            "CFA",
            "D",
            "",
            "€",
            "",
            "£",
            "£",
            "€",
            "Kr",
            "EC$",
            "€",
            "US$",
            "Q",
            "£",
            "CFA",
            "FG",
            "GY$",
            "G",
            "$",
            "L",
            "HK$",
            "Ft",
            "kr",
            "₹",//india
            "Rp",
            "SDR",
            "",
            "",
            "€",
            "£",
            "",
            "€",
            "CFA",
            "J$",
            "¥",
            "£",
            "US$",
            "",
            "",
            "T",
            "KSh",
            "$",
            "W",
            "W",
            "",
            "",
            "KN",
            "Ls",
            "",
            "M",
            "L$",
            "LD",
            "Fr.",
            "Lt",
            "€",
            "P",
            "",
            "FMG",
            "MK",
            "RM",
            "Rf",
            "CFA",
            "€",
            "€",
            "UM",
            "Rs",
            "€",
            "US$",
            "US$",
            "S",
            "",
            "€",
            "T",
            "€",
            "EC$",
            "",
            "MTn",
            "K",
            "$",
            "N$",
            "NRs",
            "NAƒ",
            "€",
            "F",
            "NZ$",
            "C$",
            "CFA",
            "₦",//Nigeria
            "NZ$",
            "$",
            "US$",
            "kr",
            "",
            "Rs.",
            "US$",
            "B./",
            "K",
            "",
            "S/.",
            "₱",//Philippines
            "NZ$",
            "",
            "€",
            "US$",
            "QR",
            "€",
            "L",
            "R",
            "RF",
            "WS$",
            "US$",
            "€",
            "Db",
            "SR",
            "CFA",
            "din.",
            "SR",
            "Le",
            "S$",
            "€",
            "€",
            "SI$",
            "Sh.",
            "R",
            "€",
            "Rs",
            "£",
            "EC$",
            "EC$",
            "EC$",
            "",
            "$",
            "kr",
            "E",
            "kr",
            "Fr.",
            "",
            "F",
            "NT$",
            "",
            "",
            "฿",//Thailand
            "US$",
            "CFA",
            "TT$",
            "DT",
            "YTL",
            "m",
            "US$",
            "$",
            "USh",
            "",
            "",
            "£",
            "US$",
            "CFA",
            "$U",
            "",
            "VT",
            "€",
            "Bs",
            "₫",//Vietnam
            "US$",
            "US$",
            "F",
            "€",
            "WS$",
            "",
            "F",
            "ZK",
            "Z$"
	};

    public static List<Currency> getData() {
        List<Currency> data = new ArrayList<>();

        for(int i = 0; i < countries.length; i++) {
            Currency item = new Currency();
            item.setCountry(countries[i]);

            if(symbols[i].equals("")) {
                item.setSymbol(isos[i]);
            }
            else {
                item.setSymbol(symbols[i]);
            }

            item.setCurrency(currencies[i]);
            item.setIso(isos[i]);
            data.add(item);
        }
        return data;
    }

}