package com.berstek.uhacpayso.staticData;

/**
 * Created by John on 11/26/2016.
 */

public class Quotes {

    public static String[] getQuotes() {
        return quotes;
    }

    public static String[] getAuthors() {
        return authors;
    }

    private static final String quotes[] = {"Early to bed, early to rise, keeps you healthy, wealthy and wise.",
            "For I don't care too much for money, for money can't buy me love.",
            "Money is like a sixth sense - and you can't make use of the other five without it.",
            "A penny saved is a penny earned.",
            "Time is more valuable than money. You can get more money, but you cannot get more time.",
            "Too many of us look upon Americans as dollar chasers. This is a cruel libel,even if it is reiterated thoughtlessly by the Americans themselves.",
            "Money, if it does not bring you happiness, will at least help you be miserable in comfort.",
            "Money is only a tool. It will take you wherever you but it will not replace you as the driver.",
            "I was so poor growing up...if I wasn't a boy...I'd have nothing to play with.",
            "A wise man should have money in his head, but not in his heart.",
            "He who marries for love without money has good nights and sorry days.",
            "Anyone who lives within their means suffers from a lack of imagination.",
            "Make money your god and it will plague you like the devil.",
            "When I was young I thought that money was the most important thing in life; now that I am old I know that it is.",
            "Money never made a man happy yet, nor will it. The more a man has, the more he wants. Instead of filling a vacuum, it makes one.",
            "Money frees you from doing things you dislike. Since I dislike doing nearly everything, money is handy.",
            "The glow of one warm thought is to me worth more than money.",
            "Money often costs too much.",
            "Money will buy you a fine dog, but only love can make it wag its tail",
            "Many people take no care of their money till they come nearly to the end of it, and others do just the same with their time.",
            "If you think nobody cares if you're alive, try missing a couple of car payments.",
            "Don't tell me where your priorities are. Show me where you spend your money and I'll tell you what they are.",
            "Formal education will make you a living; self-education will make you a fortune.",
            "If you pay peanuts, you get monkeys.",
            "Money is not the most important thing in the world. Love is. Fortunately, I love money.",
            "If you would be wealthy, think of saving as well as getting.",
            "What difference does it make how much you have? What you do not have amounts to much more.",
            "If you want to know what God thinks about money, just look at the people He gives it to.",
            "It doesn't matter if you're black or white... the only color that really matters is green.",
            "My problem lies in reconciling my gross habits with my net income.",
            "If you would know the value of money, go and try to borrow some.",
            "Money is the opposite of the weather. Nobody talks about it, but everybody does something about it.",
            "Lack of money is the root of all evil.",
            "The mint makes it first, it is up to you to make it last.",
            "Money is usually attracted, not pursued.",
            "The safest way to double your money is to fold it over and put it in your pocket.",
            "Money will come when you are doing the right thing.",
            "The chief value of money lies in the fact that one lives in a world in which it is overestimated.",
            "You use your money to buy privacy because during most of your life you aren't allowed to be normal.",
            "Money is better than poverty, if only for financial reasons.",
            "Don't tell me what you value,show me your budgetand I'll tell you what you value.",
            "It is not the man who has too little, but the man who craves more, that is poor.",
            "The art is not in making money, but in keeping it.",
            "Americans spend all or most of their income on things that have little or no lasting value!",
            "The art of living easily as to money is to pitch your scale of living one degree below your means.",
            "You must gain control over your money or the lack of it will forever control you.",
            "If we fasten our attention on what we have, rather than what we lack, a very little wealth is sufficient.",
            "Enough is better than too much.",
            "Money should be mastered, not served.",
            "Soon gotten, soon spent; ill gotten, ill spent.",
            "Someone is sitting in the shade today because someone planted a tree a long time ago.",
            "It does not matter how slowly you go as long as you do not stop.",
            "Just because you can afford it doesn't mean you should buy it.",
            "Money is a terrible master but an excellent servant.",
            "The glow of one warm thought is to me worth more than money.",
            "A goal without a timeline is just a dream.",
            "A budget is telling your money where to go instead of wondering where it went.",
            "Financial freedom is also determined by your thoughts and emotions about money and worth. I've worked with millionaires who worry just as much as people barely above the poverty line. To me, financial freedom means no worry. It means peace.",
            "It's not about having it all. It's about having what you value most.",
            "Beware of little expenses: a small leak can sink a great ship.",
            "A man's true wealth is the good he does in this world.",
            "I want the whole of Europe to have one currency;it will make trading much easier.",
            "Men do not understand how great a revenue is economy.",
            "Money is for food and clothing and the occasional splurge at the flea market when you find some nice, sustainable furniture."};

    private static final String authors[] = {"Benjamin Franklin",
            "The Beatles",
            "William Somerset Maugham",
            "Benjamin Franklin",
            "Jim Rohn",
            "Albert Einstein",
            "Helen Gurley Brown",
            "Ayn Rand",
            "Rodney Dangerfield",
            "Jonathan Swift",
            "Anonymous",
            "Oscar Wilde",
            "Henry Fielding",
            "Oscar Wilde",
            "Benjamin Franklin",
            "Groucho Marx",
            "Thomas Jefferson",
            "Ralph Waldo Emerson",
            "Richard Friedman",
            "Johann Wolfgang von Goethe",
            "Earl Wilson",
            "James W. Frick",
            "Jim Rohn",
            "James Goldsmith",
            "Jackie Mason",
            "Ben Franklin",
            "Seneca",
            "Dorothy Parker",
            "Family Guy",
            "Errol Flynn",
            "Benjamin Franklin",
            "Rebecca Johnson",
            "George Bernard Shaw",
            "Evan Esar",
            "Jim Rohn",
            "Kin Hubbard",
            "Mike Phillips",
            "H. L. Mencken",
            "Johnny Depp",
            "Woody Allen",
            "Joe Biden",
            "Seneca",
            "Proverb",
            "Thomas Stanley",
            "Sir Henry Taylor",
            "Dave Ramsey",
            "Francis Johnson",
            "French Proverb",
            "Syrus, Maxims",
            "John Heywood",
            "Warren Buffett",
            "Confucius",
            "Suze Orman",
            "P.T. Barnum",
            "Thomas Jefferson",
            "Robert Herjavec",
            "Dave Ramsey",
            "Meadow Devor",
            "Jean Chatzky",
            "Benjamin Franklin",
            "Bendixline",
            "Napoleon I",
            "Cicero",
            "Fionia"};

}
